-- E-CLASSES - BANCO SUPABASE
-- Rode este arquivo no SQL Editor do seu projeto Supabase.

create table if not exists public.teams (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null default '#6366f1'
);

create table if not exists public.games (
    id bigint generated by default as identity primary key,
    name text not null,
    genre text not null
);

create table if not exists public.competitors (
    id bigint generated by default as identity primary key,
    name text not null,
    nickname text not null,
    "teamId" bigint references public.teams(id) on update cascade on delete set null
);

create table if not exists public.matches (
    id bigint generated by default as identity primary key,
    "gameId" bigint not null references public.games(id) on update cascade on delete cascade,
    "team1Id" bigint not null references public.teams(id) on update cascade on delete cascade,
    "team2Id" bigint not null references public.teams(id) on update cascade on delete cascade,
    score1 integer not null default 0,
    score2 integer not null default 0,
    status text not null default 'scheduled',
    date timestamptz not null
);

-- Permite que a chave pública usada pela API faça as operações do trabalho.
-- Para esta etapa o foco é somente o funcionamento.
alter table public.teams enable row level security;
alter table public.games enable row level security;
alter table public.competitors enable row level security;
alter table public.matches enable row level security;

drop policy if exists "eclasses teams" on public.teams;
drop policy if exists "eclasses games" on public.games;
drop policy if exists "eclasses competitors" on public.competitors;
drop policy if exists "eclasses matches" on public.matches;

create policy "eclasses teams" on public.teams for all to anon, authenticated using (true) with check (true);
create policy "eclasses games" on public.games for all to anon, authenticated using (true) with check (true);
create policy "eclasses competitors" on public.competitors for all to anon, authenticated using (true) with check (true);
create policy "eclasses matches" on public.matches for all to anon, authenticated using (true) with check (true);

-- Dados iniciais do data.json original.
insert into public.teams (id, name, color) values
(1, 'Cyber Dragons', '#7B1FA2'),
(2, 'Neon Knights', '#00BCD4')
on conflict (id) do nothing;

insert into public.games (id, name, genre) values
(1, 'League of Legends', 'MOBA'),
(2, 'VALORANT', 'FPS'),
(3, 'Counter-Strike 2', 'FPS'),
(4, 'Rocket League', 'Esport')
on conflict (id) do nothing;

insert into public.competitors (id, name, nickname, "teamId") values
(1, 'Pedro Santos', 'Pterodactyl', 1),
(2, 'Julia Lima', 'JuliaX', 1),
(3, 'Carlos Eduardo', 'Cadu00', 2),
(4, 'Ana Oliveira', 'AnaPvP', 2)
on conflict (id) do nothing;

insert into public.matches (id, "gameId", "team1Id", "team2Id", score1, score2, status, date) values
(1, 1, 1, 2, 1, 0, 'finished', '2026-03-24T14:00:00-03:00'),
(2, 2, 2, 1, 0, 0, 'scheduled', '2026-03-25T16:00:00-03:00')
on conflict (id) do nothing;

-- Ajusta as sequências para que novos IDs continuem a partir dos maiores IDs existentes.
select setval(pg_get_serial_sequence('public.teams', 'id'), coalesce((select max(id) from public.teams), 1), true);
select setval(pg_get_serial_sequence('public.games', 'id'), coalesce((select max(id) from public.games), 1), true);
select setval(pg_get_serial_sequence('public.competitors', 'id'), coalesce((select max(id) from public.competitors), 1), true);
select setval(pg_get_serial_sequence('public.matches', 'id'), coalesce((select max(id) from public.matches), 1), true);
